Add tauri store
jojoeeeen/app-desktop pull request #7
Opened 2022-07-24 11:41 UTC by mirko-san

2022-07-30 06:49 UTC, tdyzzsp47 requested changes
後からだと面倒になる気がするのでstoreの切り出しと整理は先にやっておいた方が良さげな気がします

2022-08-07 09:33 UTC, Shinnosuke364 requested changes

2022-08-07 09:33 UTC, Shinnosuke364 commented on src/App.vue
> +      <settins-base />
settings の typo っぽいです

2022-08-07 09:33 UTC, Shinnosuke364 commented on src/components/SettingsBase.vue
> +      // await store.set('mute-words', { items: ['hello', 'world', '!']});
❓ 

ここのコメントアウトって外し忘れです？
コメントアウトされた状態でローカルで実行してみたのですが、エラーになるようです

2022-08-07 13:20 UTC, mirko-san commented on src/components/SettingsBase.vue
> +      // await store.set('mute-words', { items: ['hello', 'world', '!']});
うーーん、外し忘れではないんですけど、まったく store にデータが無いと初回ロード時にデータがないのでエラーにはなりそうですね・・・。
コメントアウトした理由としては、すでにデータがあれば毎回この関数呼ばれるときに set をする意味はないが、期待しているデータ型を示したいという理由で残しておいたのですが、どうかんがえてもわかりにくいので、もっと高度に抽象化しようと思います 🙇

2022-08-07 15:01 UTC, mirko-san commented on src/core/store.ts
> +class StoreMock {
📝 

https://github.com/tauri-apps/tauri-plugin-store/blob/dev/webview-dist/index.d.ts#L5
このあたりの型見ながら適当に定義しました

2022-08-21 11:45 UTC, Shinnosuke364 approved these changes

2022-08-21 11:52 UTC, tdyzzsp47 approved these changes

2022-08-25 09:58 UTC, merged